-- Clear jam mid animation with motion marks
-- Known bug: Is called for NPC reloads
function actor_on_hud_animation_mark(state, mark)
	if mark == "clear_jam" then
		local item = db.actor:active_item()
		if not item then return end

		local wpn = item:cast_Weapon()
		if not wpn then return end

		wpn:SetMisfire(false)
	end
end

function on_game_start()
	RegisterScriptCallback("actor_on_hud_animation_mark",actor_on_hud_animation_mark)
end
